In [24]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix,classification_report

In [25]:
data={
    "tumor_size_cm":[1.2,1.5,2.0,1.1,5.5,1.3,1.8,1.4,6.2,1.6],
    "malignant":[0,0,0,0,1,0,0,0,1,0] # 1=cancer
}

df=pd.DataFrame(data)
df

   tumor_size_cm  malignant
0            1.2          0
1            1.5          0
2            2.0          0
3            1.1          0
4            5.5          1
5            1.3          0
6            1.8          0
7            1.4          0
8            6.2          1
9            1.6          0

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   tumor_size_cm  10 non-null     float64
 1   malignant      10 non-null     int64
dtypes: float64(1), int64(1)
memory usage: 292.0 bytes

In [27]:
df.describe()

       tumor_size_cm  malignant
count       10.00000  10.000000
mean         2.36000   0.200000
std          1.86619   0.421637
min          1.10000   0.000000
25%          1.32500   0.000000
50%          1.55000   0.000000
75%          1.95000   0.000000
max          6.20000   1.000000

In [28]:
df.shape

(10, 2)

In [29]:
df.isna().sum()

tumor_size_cm    0
malignant        0
dtype: int64

In [30]:
# train test split

x=df[["tumor_size_cm"]]
y=df["malignant"]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [31]:
model=LogisticRegression()
model.fit(x_train,y_train)
prediction=model.predict(x_test)
prediction

array([1, 0])

In [32]:
y_test.values

array([1, 0])

In [33]:
cm = confusion_matrix(y_test,prediction)
print(cm)

[[1 0]
 [0 1]]